Temp
abdossamadhaghiri/messenger pull request #1
Opened 2023-08-14 07:22 UTC by abdossamadhaghiri

2023-08-14 18:59 UTC, ParSal123 commented
الان به ازای هر کدوم از ماژولای server و client، توی pom اومدی و تنظیمات رو نوشتی، یعنی parent رو ست کردی و چیزایی که می‌خواستی رو گذاشتی. به جای این تکرار، به نظرم بهتره spring-boot-starter-parent رو بیاری توی pom.xml اصلی (یعنی messenger) و بقیهٔ ماژول‌ها بچهٔ اون بشن، یعنی parentشون بشه اون pom.xml بالایی.

2023-08-14 19:08 UTC, ParSal123 requested changes

2023-08-14 19:08 UTC, ParSal123 commented on server/pom.xml
> +    </build>
نیازی به این نیست. با spring-boot-starter-parent می‌آد.

2023-08-14 19:08 UTC, ParSal123 commented on client/pom.xml
> +    </build>
نیازی به این نیست. با spring-boot-starter-parent می‌آد.

2023-08-14 19:21 UTC, ParSal123 commented on common/src/main/java/org/example/Message.java
> +    private int id;
این فیلد به چه دردی می‌خوره دقیقاً؟ private عه و getter هم نداره!

2023-08-15 07:00 UTC, ParSal123 reviewed
کلاً توی متدهای سمت سرور، نیاز به validation هست. مثلاً اگه username وجود نداشته باشه چی؟
قاعدتاً سرورت نباید exception بخوره. من یه نمونه رو تو کد مشخص کردم اما خودت نگاه کن.
در ضمن، تست هم می‌خواد، یعنی با usernameهای نامعتبر درخواست می‌زنی و باید ارور رو برگردونه.

2023-08-15 07:19 UTC, ParSal123 requested changes
در مورد maven-wrapper یه سرچ بکن. کلاً یه دونه فولدر .mvn به همراه mvnw باید وجود داشته باشه توی پروژه و اونم باید کف پروژه باشه.

2023-08-15 07:19 UTC, ParSal123 commented on client/src/main/java/com/example/client/CommandProcessor.java
> +        }
یه دکمهٔ quit بذار برای بنده خدا :))
چطوری ار برنامه بیاد بیرون.

2023-08-15 07:19 UTC, ParSal123 commented on client/src/main/java/com/example/client/CommandProcessor.java
> +    private static RestTemplate restTemplate;
در [javadoc مربوط به RestTemplate](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html) نوشته:

NOTE: As of 5.0 this class is in maintenance mode, with only minor requests for changes and bugs to be accepted going forward. Please, consider using the org.springframework.web.reactive.client.WebClient which has a more modern API and supports sync, async, and streaming scenarios.

لطفاً از مدل جدید و درستش استفاده کن. کلاً خوبه که javadocها رو ببینی چون اطلاعات اونجا معمولاً به روزتر از guide و tutorial هاست.

2023-08-15 07:19 UTC, ParSal123 commented on client/src/main/java/com/example/client/CommandProcessor.java
> +        String URL = "http://localhost:9000/messages";
این URL و بقیه که توی تابعای مختلف هستن، بهتره این شکلی hardcode نباشن. spring این قابلیت رو داره که تنظیمات رو از طریق فایل application.properties بگیره (مثل همون server.port که زدی) و تو می‌تونی کلاسِ خودت رو تعریف کنی و تنظیمات مربوط به اون رو از طریق فایل application.properties بدی. با استفاده از `@ConfigurationProperties` می‌تونی این کار رو انجام بدی.

2023-08-15 08:25 UTC, abdossamadhaghiri commented on pom.xml
> +<!--    </modules>-->
اشتباه لپی بود :)

2023-08-15 08:25 UTC, abdossamadhaghiri commented on server/src/main/java/com/example/server/Database.java
> +    }
این کلاسه که تو کامیت بعدی پاک شد کلا

2023-08-15 09:23 UTC, abdossamadhaghiri commented on common/src/main/java/org/example/Message.java
> +}
رکورد نمیشد چون کلاسی که entity میشه باید یه NoArgsConstructor داشته باشه. ولی با lombok بهتر شد.

2023-08-15 09:25 UTC, abdossamadhaghiri commented on common/src/main/java/org/example/Message.java
> +    private int id;
برا این کلاس primary key عه. بقیه فیلدها یونیک نیستن دیگه. 
البته در ادامه هم استفاده میشه برای ادیت و پاک کردن پیام و ...

2023-08-16 06:56 UTC, abdossamadhaghiri commented on server/src/main/java/com/example/server/ServerController.java
> +    private final AtomicInteger counter = new AtomicInteger();
اینم پاک شد تو کامیت بعد

2023-08-16 07:05 UTC, abdossamadhaghiri commented on server/src/main/java/com/example/server/ApplicationConfig.java
> +    }
این کلاسم پاک شد

2023-09-12 08:15 UTC, ParSal123 approved these changes

2023-09-12 08:16 UTC, ParSal123 approved these changes

2023-09-12 09:09 UTC, merged