add reply and its tests.
abdossamadhaghiri/messenger pull request #10
Opened 2023-10-04 06:54 UTC by abdossamadhaghiri

2023-10-04 09:18 UTC, ParSal123 commented
اینکه با یه فیچری، تستاش رو هم زدی نیاز به نوشتن نداره؛ یعنی بدیهیه که باید تستاش رو هم بنویسی. بنابراین نیازی نیست بگی که تستاش رو هم نوشتم، مگه اینکه نکته‌ای داشته باشه.
توی commit message منظورمه.

2023-10-04 10:46 UTC, ParSal123 requested changes

2023-10-04 10:46 UTC, ParSal123 commented on client/src/main/java/com/example/client/CommandProcessor.java
> +                .onStatus(status -> status == HttpStatus.BAD_REQUEST, clientResponse -> Mono.empty()).toEntity(String.class).block();
معمولاً تعداد . (دات) های یه خط که زیاد می‌شه، توی استایل‌های مختلف که دیدم، می‌آرن زیر هم می‌نویسن که خواناتر بشه:
```java
client.post()
        .uri(url)
        .bodyValue(messageModel)
        .retrieve()
        .onStatus(status -> status == HttpStatus.BAD_REQUEST, clientResponse -> Mono.empty())
        .toEntity(String.class)
        .block();
```

2023-10-04 10:46 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +        Message message3 = new Message(3L, "ccc", "reza", chats.get(2).getId(), 0L);
اینا کلاً بهتره با بیلدر ساخته بشن. علاوه بر اون، می‌شه برای فیلد آخر، مقدار پیش‌فرض گذاشت (صفر) که نیازی نباشه ست کنی.

2023-10-04 10:46 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +    void testNewMessage_repliedMessageDoesntExists() {
لطفاً تست‌های جدید، اسم test اولشون نداشته باشن.

2023-10-04 10:46 UTC, ParSal123 commented on server/src/main/java/com/example/server/ServerController.java
> +                return pv;
این if یکمی خوانا نیست، ctrl alt L اینا رو درست نمی‌کنه؟ اگه خودش درست نمی‌کنه، ابزارهایی هم هست که این کارا رو انجام می‌ده به جای اینکه دستی انجام بشه. مثلاً پلاگین google-java-format.

2023-10-04 10:46 UTC, ParSal123 commented on server/src/main/java/com/example/server/ServerController.java
>      }
بهتره message با بیلدر ساخته بشه.

2023-10-04 10:51 UTC, abdossamadhaghiri commented on client/src/main/java/com/example/client/CommandProcessor.java
> +
هیچی صرفا چون قرمزه و با بقیه چیزا قاطی نمیشه :))

2023-10-04 10:59 UTC, abdossamadhaghiri commented on client/src/main/java/com/example/client/CommandProcessor.java
> +
کاربر باید آیدی پیام رو وارد کنه برای ادیت و دیلیت کردن واسه همین آیدی رو چاپ می‌کنم

2023-10-04 10:59 UTC, abdossamadhaghiri commented on client/src/main/java/com/example/client/CommandProcessor.java
> +        return sendMessage(text, chatId, repliedMessageId);
الان اینجا اگه سوییچ بنویسم، هم توی کیس ۱ و هم کیس ۲ باید متود sendMessage رو کال کنم یعنی یه خط کد تکراری توی جفتش باید بیارم.
درواقع چون کیس ۱ زیرمجموعه کیس ۲ بود و کیس ۲ یه کارایی اضافه‌تر داشت، اینطوری نوشتم که مثلا از داپلیکیت‌کد جلوگیری کنم.
ولی اون یکم داپلیکیته اوکیه؟

2023-10-04 11:04 UTC, abdossamadhaghiri commented on client/src/main/java/com/example/client/CommandProcessor.java
> +                .onStatus(status -> status == HttpStatus.BAD_REQUEST, clientResponse -> Mono.empty()).toEntity(String.class).block();
الان همه اینا رو این شکلی کنم؟ هم این ریکوئست زدن‌ها هم مثلا MessageModel با Builder می‌خوام بسازم هر فیلد رو توی یه خط بیارم؟
خوانایی قبول دارم بیشتر میشه ولی الکی تعداد خط رو خیلی زیاد می‌کنه! مهم نیست؟

2023-10-04 11:20 UTC, abdossamadhaghiri commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +        Message message3 = new Message(3L, "ccc", "reza", chats.get(2).getId(), 0L);
الان کلا بیلدر خواناییش از کانستراکتور بیشتر نیست؟ چرا باید از کانستراکتور استفاده کرد پس؟ یا اصن نباید استفاده کرد و همه‌جا رو با همین بیلدر بزنم؟ :)

2023-10-04 12:16 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +        Message message3 = new Message(3L, "ccc", "reza", chats.get(2).getId(), 0L);
Effective Java Item 2 رو ببین.
این انتخابا انقدر صفر و یکی نیست. مثلاً اگه ۲ ۳ تا ورودی داشته باشی، از توی کانستراکتور معلومه چیان؛ ولی بیشتر که می‌شه دیگه قابلیت خوندن می‌آد پایین.

2023-10-04 12:21 UTC, ParSal123 commented on client/src/main/java/com/example/client/CommandProcessor.java
> +                .onStatus(status -> status == HttpStatus.BAD_REQUEST, clientResponse -> Mono.empty()).toEntity(String.class).block();
معمولاً خوانایی بیشتر می‌شه. چون دیدم خیلی از formatterها این کار رو می‌کنن (مثل همون گوگل که گفتم)، به نظرم این کار رو بکنیم. این مدل فعلی که خوب نیست. اگه ایدهٔ جدیدی داری بگو شاید زیباتر شد. :)
اگه اشتباه نکنم گوگل فرمتر می‌گه که اگه کل عبارت تو یه خط جا می‌شه بذار بمونه، اگه نه هر کدوم تو یه خط.

2023-10-04 12:24 UTC, ParSal123 commented on client/src/main/java/com/example/client/CommandProcessor.java
> +        return sendMessage(text, chatId, repliedMessageId);
آره یه خط مهم نیست. اگه خیلی گیری، می‌شه fall through نوشت که برای اینجا پیشنهاد نمی‌کنم.

2023-10-04 13:51 UTC, abdossamadhaghiri commented on client/src/main/java/com/example/client/CommandProcessor.java
> +                .onStatus(status -> status == HttpStatus.BAD_REQUEST, clientResponse -> Mono.empty()).toEntity(String.class).block();
آها

2023-10-04 14:09 UTC, abdossamadhaghiri commented on server/src/main/java/com/example/server/ServerController.java
> +                return pv;
آقا این پلاگینه که خیلی بد بود :))
غیر فعالش کردم!

2023-10-05 07:29 UTC, ParSal123 requested changes
توی تستا، تعدادی از کامنتا که نوشتم مربوط به چند تا تست می‌شه که من فقط روی یکی نوشتم. اونایی که اینطوری هستن رو برای تستایی که توی این مرج نوشتی اصلاح کن.

2023-10-05 07:29 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +    }
بعد از `expectBody()` خودش یه سری تابع آماده داره که می‌تونی استفاده کنی. مثلاً اینجا می‌شه `isEqualTo` نوشت که خواناتره.
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/test/web/reactive/server/WebTestClient.BodySpec.html

2023-10-05 07:29 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +    void testNewMessage_repliedMessageDoesntInThisChat() {
isnt

2023-10-07 10:38 UTC, abdossamadhaghiri commented on server/src/test/java/com/example/server/ServerControllerTest.java
> -                assertEquals(Commands.INVALID_MESSAGE_CONTENT, result.getResponseBody()));
نه نیاز نبود و پاکش کردم.

2023-10-07 10:47 UTC, abdossamadhaghiri commented
> توی تستا، تعدادی از کامنتا که نوشتم مربوط به چند تا تست می‌شه که من فقط روی یکی نوشتم. اونایی که اینطوری هستن رو برای تستایی که توی این مرج نوشتی اصلاح کن.

2023-10-09 11:31 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +        client.post().uri(url).bodyValue(messageModel).exchange().expectStatus().isBadRequest().expectBody(String.class).consumeWith(result ->
این مورد برای همهٔ تستایی که مربوط به این مرج هستن انجام نشده.

2023-10-09 11:41 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +        client.post().uri(url).bodyValue(messageModel).exchange().expectStatus().isBadRequest().expectBody(String.class).consumeWith(result ->
این مورد رو توی ایشوی مربوط به ریفکتور تست‌ها بنوس که یادت نره.

2023-10-09 11:45 UTC, ParSal123 commented on client/src/main/java/com/example/client/CommandProcessor.java
>          }
این مدل نوشتن زیبا نیست. بهتر نبود یه تابع (یا کلاس) کمکی وجود داشت که اینطور می‌شد نوشت؟
```java
System.out.println(YELLOW("some text") + GREEN("some other text"));
```
اینطوری نیازی به دستی نوشتن و ریست کردنشون نیست. حالا اینی که گفتم به نظرم بهتر از اونه اما اگه چیز بهتری به ذهنت می‌رسه انجام بده. یه طوری باشه که خوندنش روون باشه.

2023-10-09 11:48 UTC, ParSal123 commented
با اسم‌گذاری کامیت‌ها و کوچیک بودنشون و «برای یه هدف بودن»شون بسیار صفا کردم.

2023-10-09 11:58 UTC, abdossamadhaghiri commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +        client.post().uri(url).bodyValue(messageModel).exchange().expectStatus().isBadRequest().expectBody(String.class).consumeWith(result ->
نوشتم.

2023-10-09 12:09 UTC, abdossamadhaghiri commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +        client.post().uri(url).bodyValue(messageModel).exchange().expectStatus().isBadRequest().expectBody(String.class).consumeWith(result ->
البته newMessage_invalidSender و newMessage_chatDoesntExists و newMessage_chatIsNotInSendersChat تستایی نبودن که توی این مرج درست بشن و از قبل بودن واسه همون اینا رو دست نزده بودم.
ولی چون مربوط به ریپلای بودن اوکی درست‌شون کردم.

2023-10-09 12:45 UTC, ParSal123 commented on client/src/main/java/com/example/client/CommandProcessor.java
>          }
وظیفهٔ print کردن و زیبا print کردن به نظرم با CommandProcessor نباید باشه. یعنی اون باید کارهای منطق رو انجام بده و برای پرینت کردن، delegate کنه به یه کلاس دیگه که کارش پرینت کردنه. الان دو متدی که اضافه کردی، به کارکرد این کلاس نمی‌خورن به نظرم.

2023-10-09 15:17 UTC, ParSal123 approved these changes

2023-10-09 15:17 UTC, merged