Forward
abdossamadhaghiri/messenger pull request #15
Opened 2023-10-09 17:09 UTC by abdossamadhaghiri

2023-10-11 08:57 UTC, ParSal123 requested changes

2023-10-11 08:57 UTC, ParSal123 commented on client/src/main/java/com/example/client/CommandProcessor.java
> +            }
اگه chat وجود نداشته باشه، بهتره خطا نمایش بدیم.

2023-10-11 09:13 UTC, ParSal123 requested changes

2023-10-11 09:13 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +    }
چرا message رو دوبار ساختی؟

2023-10-11 09:13 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +    }
تو بقیهٔ تستام همینطور

2023-10-11 09:13 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +    }
indentation اینا به نظرم درست نیست
۸ تا اسپیس باید باشه.

2023-10-11 09:13 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +    void newMessage_forwardedFromUsernameDoesntExist() {
نیاز به حالت‌های تست بیشتری هست. مثلاً اینکه پیام وجود نداشته باشه، کاربر وجود نداشته باشه، مقصد وجود نداشته باشه و ....

2023-10-11 09:13 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +    }
اگه با دست اینکارو انجام می‌دی، قطعاً اشتباه می‌زنی.

2023-10-11 09:13 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +                .sender("ali")
chats و messages بهتر نیست که اون بالا توی Before باشن؟
انگار هر دفعه همون کارو داری می‌کنی.

2023-10-11 09:13 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +                .build();
چرا id و chatid رو خودت نمی‌دی؟ داخل تستا، دیتابیس دست خودته و خودت می‌دونی چی زدی توش؛ چرا باز get می‌کنی ازشون؟ آیا فک می‌کنی ممکنه بعداً تغییر کنن؟

2023-10-11 09:13 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +                .build();
چرا id و chatid رو خودت نمی‌دی؟ داخل تستا، دیتابیس دست خودته و خودت می‌دونی چی زدی توش؛ چرا باز get می‌کنی ازشون؟ آیا فک می‌کنی ممکنه بعداً تغییر کنن؟

2023-10-11 09:35 UTC, abdossamadhaghiri commented on client/src/main/java/com/example/client/CommandProcessor.java
> +        }
این کدها رو قبل‌تر نوشته بودم و از اون موقع مونده این چیزاش. بعضی از این تغییرات که تو ذهنم خیلی مهم و بلد نبوده یادم نمونده که درستش کنم!

2023-10-11 09:40 UTC, abdossamadhaghiri commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +    }
آخه برای ریکوئست زدن باید MessageModel بفرستم توی بادی. و برا اینکه چک کنم پیام اضافه شده به دیتابیس، باید چک کنم Message متناظرش توی پیام‌ها اضافه شده یا نه. و مجبورم از روی MessageModel اول، Message رو بسازم.
کار دیگه‌ای میشه کرد؟

2023-10-11 09:46 UTC, abdossamadhaghiri commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +    }
نه دستی نمی‌زنم. کار خودشه!
کلا خودش میره از زیر . (دات) خط بالایی شروع می‌کنه.

2023-10-11 10:41 UTC, abdossamadhaghiri commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +    }
خب اوکی شد. توی ایشوها می‌نویسم که درست کنم همرو بعدا

2023-10-11 10:51 UTC, abdossamadhaghiri commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +    void newMessage_forwardedFromUsernameDoesntExist() {
من فروارد رو اینطوری پیاده‌سازی کردم که اول پیام با آیدی‌ای که کاربر میگه رو می‌گیرم از سرور، و اگه وجود نداشته باشه همین‌جا می‌فهمم و ارورو میدم بهش. بعد چت مقصد رو می‌گیرم ازش و چک می‌کنم. و اگه اینا اوکی بودن، دیگه اینجاش میشه یه ارسال پیام عادی انگار. درواقع توی سرور اصن متودی برای فروارد ندارم و با ترکیب دو سه تا متود مختلف فروارد در میاد. و اینایی که گفتی توی تست‌های getMessage و اینا تست شده.

2023-10-11 10:54 UTC, abdossamadhaghiri commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +                .sender("ali")
چی بذارم توی before؟! کاری نمی‌کنم که. صرفا می‌خوام به چت‌ها و پیام‌های دیتابیس دسترسی داشته باشم

2023-10-11 10:56 UTC, abdossamadhaghiri commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +                .build();
چون نمی‌دونم آیدی‌ها رو چند بدم. قبل هر متد تست، یه‌بار همه جدول‌ها پاک میشه و دوباره ساخته میشه. ولی یه سطر توی جدول که پاک میشه، آیدیش ریست نمیشه و توی اینسرت بعدی، از آیدی بعدی استفاده می‌کنه. واسه همون آیدی اینا توی هر متد فرق داره با هم

2023-10-11 11:08 UTC, ParSal123 commented on client/src/main/java/com/example/client/CommandProcessor.java
> +        }
درست کن.

2023-10-11 13:57 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +    }
مگه تابع نداری؟ createMessageModel.
در ضمن، اسم اون تابع بهتره toMessageModel باشه. این مدل اسم‌گذاری متداول‌تره.

2023-10-11 14:02 UTC, abdossamadhaghiri commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +    }
اسمشو عوض می‌کنم حله.
ولی اون تابع یه Message می‌گیره و MessageModel متناظرشو میده. اینجا برعکسشو می‌خوام! که چون common به server وابستگی نداره، نمیشد toMessage گذاشت توی MessageModel

2023-10-11 14:18 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +    void newMessage_forwardedFromUsernameDoesntExist() {
پس اینکه پیام وجود نداره تست می‌خواد.

2023-10-11 14:19 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +                .sender("ali")
این فیلدا رو توی کلاس تعریف کن و توی before بهشون مقدار بده.

2023-10-11 14:52 UTC, abdossamadhaghiri commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +                .sender("ali")
آها. حله
فقط اینکه اینا تقریبا تو یک سوم تست‌ها استفاده شدن، یجوری نیست برا اینکه توی before بیارم؟ اگه اکثر تست‌ها نیازشون داشتن منطقی‌تر بود.

2023-10-11 15:33 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +                .sender("ali")
نه یه طوری نیست. یه سری تستا یه دیتابیسی که درست می‌کنی هم نیازی ندارن.

2023-10-11 16:17 UTC, abdossamadhaghiri commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +                .sender("ali")
انجام شد.

2023-10-12 07:13 UTC, ParSal123 approved these changes

2023-10-12 07:30 UTC, merged