add group and refactor code
abdossamadhaghiri/messenger pull request #2
Opened 2023-08-29 14:51 UTC by abdossamadhaghiri

2023-09-13 09:54 UTC, ParSal123 commented
تستای این کجاست؟
تستای پروژه اصلاً کامپایل نمی‌شه :|

2023-09-19 13:11 UTC, ParSal123 requested changes

2023-09-20 08:34 UTC, abdossamadhaghiri commented on common/src/main/java/org/example/entity/Pv.java
> +}
این‌که `@Data` یه چیزایی رو میاره که لازم نیست مثل ()hashCode بد نیست؟ یعنی اگه اکثرش استفاده بشه اوکیه و لازم نیست همش استفاده بشه؟ مثل اون *. ایمپورت کردن نیست که یه چیزایی میاره که بدرد نمی‌خوره و بد باشه؟

2023-09-20 09:17 UTC, ParSal123 commented on common/src/main/java/org/example/entity/Pv.java
> +}
hashCode چرا بده؟
بعدشم چون equals رو داری override می‌کنی باید Hashcode رو هم override کنی.
Effective Java Item 11

2023-09-23 05:52 UTC, abdossamadhaghiri commented on common/src/main/java/org/example/entity/Pv.java
> +}
همون hashCode و equals جفتش با هم منظورم بود.
از این جهت گفتم که استفاده‌ای نکردم ازشون

2023-09-23 06:04 UTC, abdossamadhaghiri commented on common/src/main/java/org/example/entity/Pv.java
> +import lombok.*;
خود اینتلیج بعد از چند بار خودش اتومات *. ایمپورت می‌کنه! حالا من عوضشون کردم الان.

2023-09-23 06:39 UTC, ParSal123 commented on common/src/main/java/org/example/entity/Pv.java
> +}
اگه equals داشته باشی، منطقیه دیگه. بدون equals، رفتار پیش‌فرض اینه که آدرس ۲ تا چیز رو با هم مقایسه می‌کنه که احتمالاً درست نیست. ولی اگه first و second یکی باشن احتمالاً دو تا چت یکی هستن. یعنی هیچ جا این مقایسه به دردت نمی‌خوره؟

2023-09-23 06:40 UTC, ParSal123 commented on common/src/main/java/org/example/entity/Pv.java
> +import lombok.*;
تو تنظیمات یه دکمه‌ای داره که می‌گه هیچ وقت این کارو نکن. می‌تونی بزنی.

2023-09-25 10:22 UTC, ParSal123 requested changes

2023-09-25 10:22 UTC, ParSal123 commented on common/src/main/java/org/example/model/PvModel.java
> +}
این رو می‌شه با `@SuperBuilder` در آورد. نیازی نیست چیزی دستی بنویسی.

2023-09-25 10:22 UTC, ParSal123 commented on common/src/main/java/org/example/model/MessageModel.java
> +}
`@Value`

2023-09-25 10:22 UTC, ParSal123 commented on common/src/main/java/org/example/model/GroupModel.java
> +}
اینو می‌شه با `@SuperBuilder` درآورد.

2023-09-25 10:22 UTC, ParSal123 commented on client/src/main/java/com/example/client/ServerAddress.java
> +}
دونه دونه `@Value` نده. بذار بالای کلاس. فک کنم داشتی ور می‌رفتی باهاش یادت رفته درستش کنی.

2023-09-25 10:22 UTC, ParSal123 commented on client/src/main/java/com/example/client/CommandProcessor.java
> +                default -> System.out.println(Commands.INVALID_COMMAND);
زیبا. از فیچرهای جاوا در نسخه‌های جدیدتر.

2023-09-25 12:16 UTC, abdossamadhaghiri commented on common/src/main/java/org/example/model/MessageModel.java
> +}
تو کامیت بعدی یکی‌شون نیاز به Setter پیدا می‌کنه!

2023-09-25 12:24 UTC, ParSal123 commented on common/src/main/java/org/example/model/MessageModel.java
> +}
اونی که می‌خواد رو @Setter بذار.

2023-09-25 12:24 UTC, ParSal123 commented on common/src/main/java/org/example/model/MessageModel.java
> +}
یا حتی روی کلش @Data بذار.

2023-09-25 12:33 UTC, ParSal123 approved these changes

2023-09-25 12:34 UTC, merged