Urls
abdossamadhaghiri/messenger pull request #34
Opened 2023-10-16 07:16 UTC by abdossamadhaghiri

2023-10-16 09:09 UTC, ParSal123 requested changes

2023-10-16 10:52 UTC, abdossamadhaghiri commented on client/src/main/java/com/example/client/ApiAddresses.java
> +        messagesApiUrl = serverAddress.getAddress() + ":" + serverAddress.getPort() + UrlPaths.MESSAGES_URL_PATH;
از baseUrl استفاده کردم.

2023-10-16 11:05 UTC, abdossamadhaghiri commented on client/src/main/java/com/example/client/CommandProcessor.java
> +        String url = apiAddresses.getUsersApiUrl() + File.separator + username;
سونار وارنینگ داده بود که هارد کد نکن اسلش رو. سرچ کردم که جاش چی می‌ذارن دیدم File.separator می‌ذارن ظاهرا.

2023-10-16 11:11 UTC, abdossamadhaghiri commented on server/src/main/java/com/example/server/ServerController.java
> +    public ResponseEntity<UserModel> getUser(@PathVariable String username) {
نفهمیدم.
الانم با GET /users/1 یوزر با یوزرنیم 1 رو برمی‌گردونه دیگه.
من فعلا لاگینم توی سرور نکته خاصی نداره و یکی که لاگین می‌کنه، سمت سرور اتفاق خاصی نمیفته (یعنی سرور یوزرهای لاگین‌شده رو جداگانه نداره فعلا)
واسه همون لاگین عملا میشه همون get کردن یوزر دیگه.

2023-10-16 11:16 UTC, abdossamadhaghiri commented on server/src/main/java/com/example/server/ServerController.java
> +    public ResponseEntity<String> newUser(@RequestBody String username) {
اینم نفهمیدم چیه نکته‌اش.
میگی چرا توی بادی فقط یوزرنیم رو فرستادم نه خود یوزر رو؟

2023-10-17 05:36 UTC, ParSal123 requested changes
همچنان File.separator چیز خوبی نیست. حالا همه جا / بذاری هم طوری نمی‌شه.
دیگه بخوای خیلی منت بذاری سر sonar، یه public static final SLASH = '/' تعریف کن.
https://stackoverflow.com/questions/2417485/difference-between-file-separator-and-slash-in-paths

2023-10-17 06:31 UTC, ParSal123 approved these changes

2023-10-17 06:31 UTC, merged