Add chats in user
abdossamadhaghiri/messenger pull request #35
Opened 2023-10-17 07:15 UTC by abdossamadhaghiri

2023-10-17 10:35 UTC, ParSal123 requested changes

2023-10-17 10:35 UTC, ParSal123 commented on client/src/main/java/com/example/client/CommandProcessor.java
> +                if (chat instanceof PvModel pv && (pv.getFirst().equals(username) || pv.getSecond().equals(username))) {
فک کنم موقع signIn، فیلد userModel رو ست می‌کنی. چرا دوباره اینجا می‌گیریش؟

2023-10-17 10:35 UTC, ParSal123 commented on server/src/main/java/com/example/server/ServerController.java
>          }
اینجا به نظرم ناخواناتر شده!
دلیلش چی بوده که isInChats رو حذف کردی؟ یه متد کمکی ساده بود که جاهایی که نیاز بود، کد رو خواناتر می‌کرد.

2023-10-17 11:48 UTC, abdossamadhaghiri commented on client/src/main/java/com/example/client/CommandProcessor.java
> +                if (chat instanceof PvModel pv && (pv.getFirst().equals(username) || pv.getSecond().equals(username))) {
آره ولی چون توی تابع canStartNewChat که قبل از این getChatId هست، post می‌زنه روی pv ها و یه pv به چت‌های یوزره اضافه می‌کنه، اون یوزر مدله باید آپدیت شه تا این pv رو هم داشته باشه.
البته اینکه تابع canStartNewChat میاد post می‌زنه خوب نیست که درستش کردم و تو مرج‌های بعدی اوکی میشه.

2023-10-17 13:14 UTC, ParSal123 commented on client/src/main/java/com/example/client/CommandProcessor.java
> +                if (chat instanceof PvModel pv && (pv.getFirst().equals(username) || pv.getSecond().equals(username))) {
همونجا که post می‌زنی، نمی‌شه به onlineUser اون چت رو اضافه کنی؟ که دوباره ریکوئست نزنی.

2023-10-17 13:16 UTC, ParSal123 commented on server/src/main/java/com/example/server/ServerController.java
>          }
همممم.
حداقل کاری که اینجا می‌شه کرد اینه که اون قسمتی که توی contains اومده رو کشید بیرون و متغیر کرد:
```java
chatRepository.findById(message.get().getChatId()).get()
```

2023-10-17 13:22 UTC, ParSal123 commented on server/src/main/java/com/example/server/entity/User.java
> +
اون annotationهای بالاش هر کدوم برای چی هستن؟

2023-10-18 13:24 UTC, abdossamadhaghiri commented on client/src/main/java/com/example/client/CommandProcessor.java
> +                if (chat instanceof PvModel pv && (pv.getFirst().equals(username) || pv.getSecond().equals(username))) {
نمی‌تونم chatModel رو خودم اضافه کنم به onlineUser. چون آیدی‌شو نمی‌دونم چنده. بازم باید ریکوئس بزنم به سرور و سرور چت رو اضافه کنه به یوزری که آنلاینه. که همون getUser رو دوباره باید بیارم و فرقی نمی‌کنه.
البته این تابع getChatId اصن در ادامه پاک میشه تو مرج بعدی!

2023-10-18 13:44 UTC, abdossamadhaghiri commented on server/src/main/java/com/example/server/ServerController.java
>          }
نمیشه اینم! چون اون message ممکنه empty باشه واسه همون قبل اینکه isEmpty بودنش چک شه نمیشه get کردش و توی تعریف اون چته استفاده کرد ازش.

2023-10-18 14:01 UTC, abdossamadhaghiri commented on server/src/main/java/com/example/server/entity/User.java
> +
اون manyToMany که باید باشه وگرنه فیلده Basic attribute حساب میشه و نمی‌تونه لیست باشه.
اون joinCoumn هم که برا اینه که اون ستون با یه entity دیگه باید join بشه.
اون یکی هم که سیاست حذف رو داره مشخص می‌کنه که cascade باشه

2023-10-19 10:31 UTC, ParSal123 approved these changes

2023-10-19 10:32 UTC, merged