Add messages in chat
abdossamadhaghiri/messenger pull request #36
Opened 2023-10-19 10:56 UTC by abdossamadhaghiri

2023-10-19 11:22 UTC, ParSal123 requested changes

2023-10-19 11:22 UTC, ParSal123 commented on common/src/main/java/org/example/model/ChatModel.java
> +    private List<MessageModel> messages;
چرا Long نیاز به setter داره؟ جایی استفاده نشده انگار به جز موقع ساختن بچه‌هاش.
به جای این، می‌شد اینجا constructor بذاری و توی بچه‌ها super رو صدا کنی.

2023-10-19 11:49 UTC, abdossamadhaghiri commented on common/src/main/java/org/example/model/ChatModel.java
> +    private List<MessageModel> messages;
آره نیاز نداشت. پاکش کردم.

2023-10-19 11:56 UTC, ParSal123 requested changes

2023-10-19 11:56 UTC, ParSal123 commented on server/src/main/java/com/example/server/entity/Group.java
> +    }
هدف از این تابع چیه؟ این بیشتر به clone می‌خوره.

2023-10-19 11:56 UTC, ParSal123 commented on server/src/main/java/com/example/server/ServerController.java
> +        }
قاعتداً اگه طرف دسترسی نداشت، باید 403 بدی. اگه اون چت وجود نداشت 404.

2023-10-19 13:15 UTC, abdossamadhaghiri commented on server/src/main/java/com/example/server/entity/Group.java
> +    }
شبیه همون کلونه فقط آبجکت از یه جنس دیگه می‌سازه. group رو به groupModel متناظرش تبدیل می‌کنه. الان چون model هام با entity هام فرقی ندارن، عملا داره کپی می‌کنه اونو.
توی سرور جایی که می‌خوام آبجکت entity رو برگردونم، تبدیلش می‌کنم به model اش و اونو تو بادی برمی‌گردونم.

2023-10-19 15:48 UTC, abdossamadhaghiri commented on server/src/main/java/com/example/server/ServerController.java
> +        }
اوهوم. در مرج بعد اوکی می‌کنم

2023-10-21 09:32 UTC, ParSal123 approved these changes

2023-10-21 09:33 UTC, merged