merge with (add edit $ delete message) commit
abdossamadhaghiri/messenger pull request #4
Opened 2023-09-25 13:29 UTC by abdossamadhaghiri

2023-09-25 15:52 UTC, ParSal123 requested changes

2023-09-25 15:52 UTC, ParSal123 commented on common/src/main/java/org/example/model/MessageModel.java
> +import lombok.*;
نکن آقا!

2023-09-25 15:52 UTC, ParSal123 commented on client/src/main/java/com/example/client/CommandProcessor.java
>                  System.out.println(Commands.INVALID_COMMAND);
switch.

2023-09-25 15:52 UTC, ParSal123 commented on client/src/main/java/com/example/client/ApiAddresses.java
> +    public String getMessageApiUrl;
و کلاً یه نکته‌ای هست: بهتره متغیرا private باشن و getter داشته باشن. اگه فردا به هر دلیلی بخوای یه طوری دیگه return کنی، با مدل public نمی‌تونی. البته این احتمال توی این مثال زیاد نیستا؛ ولی فرض کن مثلاً از این به بعد می‌خوای هر چیزی رو که return می‌کنی، اسم سرور رو از اول برداری، یا مثلاً یه / تهش اضافه کنی که راحت بچسبه به path بعدی.
اینجا شاید اونقد مهم نباشه ولی تو ذهن آدم باشه خوبه.
پیاده‌سازیشم اصلاً سخت نیست وقتی lombok داری.

2023-09-25 15:52 UTC, ParSal123 commented on common/src/main/java/org/example/model/MessageModel.java
من هنوز متوجه نشدم چرا `@Getter` ها رو نمی‌بری روی کلاس.
این رو اصلاً می‌شه `@Data` کرد.

2023-09-25 15:52 UTC, ParSal123 commented on server/src/main/java/com/example/server/ServerController.java
> +    }
مدل شماره‌گذاری messageIdها چیه؟
الان من id یه پیامی که یکی دیگه فرستاده رو بدم، پاک می‌شه؟

2023-09-25 15:52 UTC, ParSal123 commented on server/src/main/java/com/example/server/ServerController.java
> +    }
مدل شماره‌گذاری messageIdها چیه؟
الان من id یه پیامی که یکی دیگه فرستاده رو بدم، می شه ادیت کرد؟

2023-09-25 15:52 UTC, ParSal123 commented on server/src/main/java/com/example/server/ServerController.java
> +    }
مدل شماره‌گذاری messageIdها چیه؟
الان من id یه پیامی که یکی دیگه فرستاده رو بدم، می‌تونم بگیرم؟

2023-09-25 15:52 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +    }
توی تست‌ها، بهتر نیست از ApiAddress استفاده کنیم؟

2023-09-25 15:52 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +                assertEquals("the message doesnt exist!", result.getResponseBody()));
این پیام‌ها بهتره که متغیر باشن. اگه بخوای عوضشون کنی، الان باید همه جا رو عوض کنی.

2023-09-25 15:52 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +                assertThat(result.getResponseBody()).usingRecursiveComparison().isEqualTo(expected));
چرا usingRecursiveComparison؟

2023-09-26 12:57 UTC, abdossamadhaghiri commented on server/src/main/java/com/example/server/ServerController.java
> +    }
مدل خاصی نداره! هر پیام جدید یدونه به آیدی آخرین پیام اضافه می‌کنه.
اگه دستی ریکوئست بزنی به سرور آره پاک می‌کنه. چیکارش باید کنم؟

2023-09-26 13:17 UTC, abdossamadhaghiri commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +                assertThat(result.getResponseBody()).usingRecursiveComparison().isEqualTo(expected));
چون assertEquls رفرنس دو تا آبجکتو مقایسه می‌کرد. البته بعدا فهمیدم equal و hashcode رو میشه استفاده کرد. ولی حالا این RecursiveComparison هم میاد تک‌تک فیلدها رو مقایسه می‌کنه. بد که نیست؟

2023-09-26 13:18 UTC, abdossamadhaghiri commented on common/src/main/java/org/example/model/MessageModel.java
> +import lombok.*;
رفتم تو تنظیمات و درستش کردم بالاخره :)

2023-09-26 14:07 UTC, ParSal123 commented on server/src/main/java/com/example/server/ServerController.java
> +    }
خب نباید پاک کنه دیگه...
الان یه public api داری که هر کسی می‌تونه هر پیامی رو پاک کنه اگه idش رو داشته باشه.
اصلاً یکی بیاد فور بزنه رو idها، کل پیام‌رسان رو پاک می‌کنه :))
مثلاً باید چک کنی اون پیام مال خودش باشه هر کی هست.

2023-09-26 14:08 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +    }
اگه تو common باشه چطور؟

2023-09-26 14:08 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +                assertThat(result.getResponseBody()).usingRecursiveComparison().isEqualTo(expected));
حتماً یه استفاده‌ای داشته که تعریفش کردن بالاخره. بد که نیست. ولی چه کاریه وقتی می‌شه بدیهی نوشت assertEquals؟؟

2023-09-27 06:25 UTC, abdossamadhaghiri commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +    }
آخه یکی نیست سورس‌شون. تو کلاینت پورت رو از فایل properties. باید بخونه ولی تو تستای سرور یه پورت رندوم جنریت کنه.

2023-09-28 09:46 UTC, ParSal123 requested changes

2023-09-28 11:30 UTC, ParSal123 requested changes

2023-09-28 11:30 UTC, ParSal123 commented on client/src/main/java/com/example/client/CommandProcessor.java
> +                }
در مورد ۲ و ۳ اگه چیزی که وارد می‌شه عدد نباشه باید خطای مناسب نشون داده بشه.
بعد از اینکه اضافه شد، تست هم اضافه بشه.

2023-09-28 11:30 UTC, ParSal123 commented on server/src/main/java/com/example/server/ServerController.java
> +            return new ResponseEntity<>(Commands.MESSAGE_DOESNT_YOUR_MESSAGE, HttpStatus.BAD_REQUEST);
این سه حالت نیاز به تست دارن.

2023-09-28 11:30 UTC, ParSal123 commented on server/src/main/java/com/example/server/ServerController.java
> +            return new ResponseEntity<>(Commands.MESSAGE_DOESNT_YOUR_MESSAGE, HttpStatus.BAD_REQUEST);
این سه حالت خطا نیاز به تست دارن.

2023-09-28 11:30 UTC, ParSal123 commented on server/src/main/java/com/example/server/ServerController.java
> +    }
حالت‌های خطا نیاز به تست دارن.

2023-09-28 11:30 UTC, ParSal123 commented on server/src/main/java/com/example/server/repository/MessageRepository.java
> -public interface MessageRepository extends JpaRepository<Message, Integer> {
چرا Long؟

2023-09-28 14:23 UTC, abdossamadhaghiri commented on common/src/main/java/org/example/model/MessageModel.java
آخه setter هم میاره برا همه. من فقط برا text می‌خوام و باید ۳ تا فیلد دیگه رو exclude کنم و مجموعا تعداد خط‌هاش بیشتر میشه!

2023-09-28 14:26 UTC, abdossamadhaghiri commented on common/src/main/java/org/example/model/MessageModel.java
اوکی @Data گذاشتم براش ولی چون برا ۳ تا فیلد دیگه غیر text باید setter رو exclude کنم، مجموعا تعداد خط‌هاش فرقی نمی‌کنه

2023-09-28 14:29 UTC, abdossamadhaghiri commented on common/src/main/java/org/example/model/MessageModel.java
>  }
براش @Data گذاشتم. ولی کلا این کلاسا رو @value نمیشه کرد چون @NoArgsConstructor لازم دارن

2023-09-28 14:35 UTC, abdossamadhaghiri commented on server/src/main/java/com/example/server/entity/Group.java
>  @Data
آره توش داره ولی چون این کلاس یه کلاس دیگه رو اکستند می‌کنه برای @equals باید بگی بره واسه پدرشو نگاه کنه یا نه. یعنی این خط رو خودش اضافه کرد اصن. بدون این وارنینگ می‌داد. و false هم برا اینکه تو کلاس پدرش که chat باشه نداریم @equals رو و باید همین کلاسو درنظر بگیره

2023-09-28 14:46 UTC, abdossamadhaghiri commented on server/src/main/java/com/example/server/repository/MessageRepository.java
> -public interface MessageRepository extends JpaRepository<Message, Integer> {
پس چی؟!

2023-09-30 07:04 UTC, abdossamadhaghiri commented on client/src/main/java/com/example/client/CommandProcessor.java
> +                }
آره اینو درستش کردم. فقط تست برا کلاینت ننوشتم کلا. خیلی قابل تست هم نیست به اون صورت

2023-09-30 09:18 UTC, ParSal123 commented on common/src/main/java/org/example/model/MessageModel.java
آیا قراره این کلاس mutable باشه یا نه؟ اگه قرار نیست باشه، پس کلاً چرا setter داره. اگه قراره mutable باشه، پس دیگه همهٔ فیلدا mutableن. اینطوری نیازی نیست exclue کنی. 
نکتهٔ بعدی اینکه با چیزایی مثل true=toBuilder می‌شه این رو حل کرد و کلاس رو کلاً immutable تعریف کرد:
https://projectlombok.org/features/Builder

2023-09-30 09:18 UTC, ParSal123 commented on common/src/main/java/org/example/model/MessageModel.java
>  }
جفتش رو با با هم بذاری نمی‌شه؟

2023-09-30 09:19 UTC, ParSal123 commented on server/src/main/java/com/example/server/entity/Group.java
>  @Data
چرا توی کلاس پدرش equals نذاشتی؟ منطقی نیست داشته باشه؟

2023-09-30 13:42 UTC, abdossamadhaghiri commented on common/src/main/java/org/example/model/MessageModel.java
>  }
نه

2023-10-01 07:55 UTC, ParSal123 commented on common/src/main/java/org/example/model/MessageModel.java
>  }
چرا نمی‌شه؟

2023-10-01 07:56 UTC, ParSal123 commented on server/src/main/java/com/example/server/entity/Pv.java
>  @Data
حالا که اینا رو عوض کردی و توی پدرش equals داره، دیگه اصلاً نیازی به equalsAndHashCode اینجا نیست. و توی گروه هم همینطور

2023-10-01 07:59 UTC, ParSal123 commented on client/src/main/java/com/example/client/CommandProcessor.java
> +                }
قابل تست که هست. منتها چون گفتیم سمت سرور تست بنویسیم و کلاینت نمی‌خواد، این مورد حله.

2023-10-01 08:20 UTC, ParSal123 commented on server/src/main/java/com/example/server/Commands.java
> +    public static final String MESSAGE_DOESNT_YOUR_MESSAGE = "the message doesnt your message!";
message isn't your message.

2023-10-01 09:04 UTC, ParSal123 commented on server/src/main/java/com/example/server/entity/Message.java
> +        return new MessageModel(((long) this.id), this.text, this.sender, this.chatId);
(long) نیازی نیست

2023-10-01 09:10 UTC, ParSal123 commented on common/src/main/java/org/example/model/MessageModel.java
این رو mutable کردی. من بودم immutable می‌کردم با toBuilder. ولی اوکیه.

2023-10-01 09:11 UTC, ParSal123 commented on server/src/main/java/com/example/server/entity/Group.java
>  @Data
این هم بهتر نیست `@Data` باشه؟

2023-10-01 09:12 UTC, ParSal123 commented on server/src/test/java/com/example/server/ServerControllerTest.java
> +        String url = HOST + port + ApiAddresses.NEW_GROUP_API_URL;
بهتر شد. هر چند ایده‌آل نیست هنوز. ولی برای این مرج کافیه.

2023-10-02 13:42 UTC, abdossamadhaghiri commented on common/src/main/java/org/example/model/MessageModel.java
>  }
خب شد. باید یه (force = true) به` @NoArgsConstructor ` اضافه کرد فقط.
الان ‌@Data رو پاک کردم و @Value گذاشتم. فقط` @AllArgsConstructor` هم باز نیاز بود با اینکه توی @Value هست. بخاطر فورس کردن noArgs

2023-10-02 14:06 UTC, abdossamadhaghiri commented on server/src/main/java/com/example/server/entity/Group.java
>  @Data
انجام شد.

2023-10-02 14:07 UTC, abdossamadhaghiri commented on server/src/main/java/com/example/server/entity/Pv.java
>  @Data
آره نیازی نیست ولی وارنینگ میده بازم بدون این. ظاهرا همین‌که ساب کلاسه، باید اینو بذاری و بگی مثل پدرش باشه یا نه.

2023-10-02 14:21 UTC, abdossamadhaghiri commented on server/src/main/java/com/example/server/Commands.java
> +    public static final String MESSAGE_DOESNT_YOUR_MESSAGE = "the message doesnt your message!";
:))

2023-10-02 14:25 UTC, abdossamadhaghiri commented on server/src/main/java/com/example/server/entity/Message.java
> +        return new MessageModel(((long) this.id), this.text, this.sender, this.chatId);
انجام شد.

2023-10-02 16:35 UTC, ParSal123 commented on client/src/main/java/com/example/client/CommandProcessor.java
> +        ResponseEntity<String> response = client.put().uri(url).header(HttpHeaders.AUTHORIZATION, onlineUsername.getToken()).bodyValue(newMessageModel).retrieve()
اینجا برای خوانایی بهتره که بیلدر بذاری. تعداد فیلدای داخل کانستراکتور زیاده و خوانایی رو می‌آره پایین.
همون toBuilder که قبل‌تر گفتم بهتر نیست؟

2023-10-03 11:42 UTC, abdossamadhaghiri commented on client/src/main/java/com/example/client/CommandProcessor.java
> +        ResponseEntity<String> response = client.put().uri(url).header(HttpHeaders.AUTHORIZATION, onlineUsername.getToken()).bodyValue(newMessageModel).retrieve()
انجام شد.

2023-10-04 05:49 UTC, ParSal123 approved these changes

2023-10-04 05:51 UTC, merged